/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary": "#505f76",
        "surface-container-highest": "#dae2fd",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "on-tertiary-fixed-variant": "#41474e",
        "on-tertiary-container": "#bfc5cd",
        "outline-variant": "#c7c4d7",
        "inverse-surface": "#283044",
        "surface-container": "#eaedff",
        "primary-container": "#4338ca",
        "tertiary": "#353b41",
        "secondary-fixed-dim": "#b7c8e1",
        "error": "#ba1a1a",
        "inverse-primary": "#c3c0ff",
        "secondary-container": "#d0e1fb",
        "secondary-fixed": "#d3e4fe",
        "on-background": "#131b2e",
        "on-error-container": "#93000a",
        "on-surface-variant": "#464554",
        "inverse-on-surface": "#eef0ff",
        "primary-fixed": "#e3dfff",
        "on-primary-container": "#c1beff",
        "primary": "#2a14b4",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed": "#0b1c30",
        "on-primary-fixed": "#100069",
        "surface-dim": "#d2d9f4",
        "on-primary": "#ffffff",
        "on-surface": "#131b2e",
        "on-secondary-container": "#54647a",
        "surface-container-high": "#e2e7ff",
        "surface-variant": "#dae2fd",
        "tertiary-fixed": "#dde3eb",
        "on-primary-fixed-variant": "#372abf",
        "outline": "#777586",
        "surface": "#faf8ff",
        "tertiary-fixed-dim": "#c1c7cf",
        "on-error": "#ffffff",
        "tertiary-container": "#4c5259",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5148d7",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-fixed": "#161c22",
        "background": "#faf8ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "margin": "2rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-sm": ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "code-md": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "code-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
